export default [
    "/",
    "/us",
    "/infos",
    "/service",
    "/coorp",
    "/black",
    "/contact",
    "/admin",
    "/api/customer/getAllCustomers",
    "/api/customer/addCustomer",

    // "/api/baseData/exportBaseStudents",
    // "/api/baseData/exportBaseTeachers",
    // "/api/baseData/exportBaseParents",
    // "/api/baseData/exportBaseParentStudent",
    // "/api/baseData/exportTranscripts",
    // "/api/ann/exportScientificDirect",
    // "/api/ann/exportCompetition",
    // "/api/ann/exportRecruit",
]
